In [36]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [4]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
median_bedroom = df.bedrooms.median()
median_bedroom

4.0

In [10]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [23]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']].values,df.price.values)

LinearRegression()

In [20]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [21]:
reg.intercept_

221323.00186540437

In [25]:
reg.predict([[3000,3,15]])

array([579201.19929613])

In [26]:
reg.predict([[3300,3,5]])

array([645137.1109651])

In [27]:
df1 = pd.read_csv("hiring.csv")
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [37]:
df1.experience = df1.experience.fillna("zero")
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [38]:
import math
median_test_score = math.floor(df1['test_score(out of 10)'].mean())
median_test_score

7

In [39]:
df1['test_score(out of 10)'] = df1['test_score(out of 10)'].fillna(median_test_score)
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [40]:
reg1 = linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']].values,df1['salary($)'].values)

LinearRegression()

In [42]:
reg1.predict([[2,9,6]])

array([53713.86677124])

In [43]:
reg1.predict([[12,10,10]])

array([93747.79628651])

In [ ]:
|